schema_version: 1

context:
  name: clypi
  version: "1.8.1"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/clypi-${{ version }}.tar.gz
  sha256: 9efa0a5a0e3668dd390e0d90321587dcb8eea12e28facd2ac437383f0de3dc76

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling ==1.27.0
    - pip
  run:
    - python >=${{ python_min }}
    - python-dateutil >=2.9.0.post0
    - typing_extensions >=4.4.0

tests:
  - python:
      imports:
        - clypi
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/danimelchor/clypi
  summary: Your all-in-one for beautiful, lightweight, prod-ready CLIs
  documentation: https://danimelchor.github.io/clypi/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
